//! TOML generation from deduplicated struct/enum/mapping data.

use std::collections::HashMap;

use crate::dedup::{UniqueEnum, UniqueStruct};
use crate::types::{ReflectedField, total_elements};

/// Resolved field type reference.
enum FieldRef {
    Struct(String),
    Enum(String),
}

/// Resolve a struct field's type_name to the correct unique TOML key.
/// When there are multiple parameterizations, match by field width.
fn resolve_struct_ref(
    sv_name: &str,
    field_width: u32,
    keys_by_sv_name: &HashMap<&str, Vec<&str>>,
    by_key: &HashMap<&str, &UniqueStruct>,
) -> Option<FieldRef> {
    let keys = keys_by_sv_name.get(sv_name)?;
    if keys.len() == 1 {
        return Some(FieldRef::Struct(keys[0].to_string()));
    }
    for key in keys {
        if let Some(s) = by_key.get(key)
            && s.total_width == field_width
        {
            return Some(FieldRef::Struct(key.to_string()));
        }
    }
    None
}

/// Resolve an enum field's type_name to the correct unique TOML key.
fn resolve_enum_ref(
    sv_name: &str,
    field_width: u32,
    keys_by_sv_name: &HashMap<&str, Vec<&str>>,
    by_key: &HashMap<&str, &UniqueEnum>,
) -> Option<FieldRef> {
    let keys = keys_by_sv_name.get(sv_name)?;
    if keys.len() == 1 {
        return Some(FieldRef::Enum(keys[0].to_string()));
    }
    for key in keys {
        if let Some(e) = by_key.get(key)
            && e.inner.width == field_width
        {
            return Some(FieldRef::Enum(key.to_string()));
        }
    }
    None
}

/// Resolve a field's type reference to its unique TOML key.
fn resolve_field_ref(
    field: &ReflectedField,
    struct_keys_by_sv_name: &HashMap<&str, Vec<&str>>,
    struct_by_key: &HashMap<&str, &UniqueStruct>,
    enum_keys_by_sv_name: &HashMap<&str, Vec<&str>>,
    enum_by_key: &HashMap<&str, &UniqueEnum>,
) -> Option<FieldRef> {
    let total_elems = total_elements(&field.array_dims);
    let elem_width = if total_elems > 1 {
        field.width / total_elems
    } else {
        field.width
    };
    match field.kind.as_str() {
        "struct" => resolve_struct_ref(
            &field.type_name,
            elem_width,
            struct_keys_by_sv_name,
            struct_by_key,
        ),
        "enum" => resolve_enum_ref(
            &field.type_name,
            elem_width,
            enum_keys_by_sv_name,
            enum_by_key,
        ),
        _ => None,
    }
}

/// A signal-to-struct mapping entry for TOML output.
pub struct MappingEntry {
    pub pattern: String,
    pub struct_type: String,
    pub array_dims: Vec<u32>,
}

/// Generate TOML string from deduplicated structs, enums, and mappings.
pub fn generate_toml(
    structs: &[UniqueStruct],
    enums: &[UniqueEnum],
    mappings: &[MappingEntry],
) -> String {
    // Build lookup maps.
    let struct_by_key: HashMap<&str, &UniqueStruct> =
        structs.iter().map(|s| (s.key.as_str(), s)).collect();
    let struct_keys_by_sv_name: HashMap<&str, Vec<&str>> = {
        let mut m: HashMap<&str, Vec<&str>> = HashMap::new();
        for s in structs {
            m.entry(&s.sv_name).or_default().push(&s.key);
        }
        m
    };
    let enum_by_key: HashMap<&str, &UniqueEnum> =
        enums.iter().map(|e| (e.key.as_str(), e)).collect();
    let enum_keys_by_sv_name: HashMap<&str, Vec<&str>> = {
        let mut m: HashMap<&str, Vec<&str>> = HashMap::new();
        for e in enums {
            m.entry(&e.inner.name).or_default().push(&e.key);
        }
        m
    };

    let mut out = String::new();
    out.push_str("# Generated by surfer-struct-gen\n");
    out.push_str("# Do not edit manually — regenerate from SystemVerilog sources.\n\n");

    // Enums.
    if !enums.is_empty() {
        out.push_str(
            "# ── Enums ──────────────────────────────────────────────────────────────────────\n\n",
        );
        for e in enums {
            out.push_str(&format!("[enums.{}]\n", e.key));
            out.push_str(&format!("width = {}\n", e.inner.width));
            out.push_str("values = { ");
            let pairs: Vec<String> = e
                .inner
                .values
                .iter()
                .map(|v| format!("\"{}\" = \"{}\"", v.binary, v.name))
                .collect();
            out.push_str(&pairs.join(", "));
            out.push_str(" }\n\n");
        }
    }

    // Structs.
    if !structs.is_empty() {
        out.push_str(
            "# ── Structs ────────────────────────────────────────────────────────────────────\n",
        );
        out.push_str("# Fields listed MSB-first (Verilator packing order)\n\n");
        for s in structs {
            out.push_str(&format!("# {}: {} bits\n", s.key, s.total_width));
            out.push_str(&format!("[structs.{}]\n", s.key));
            for f in &s.fields {
                out.push_str(&format!("[[structs.{}.fields]]\n", s.key));
                out.push_str(&format!("name = \"{}\"\n", f.name));

                let resolved = resolve_field_ref(
                    f,
                    &struct_keys_by_sv_name,
                    &struct_by_key,
                    &enum_keys_by_sv_name,
                    &enum_by_key,
                );

                match resolved {
                    Some(FieldRef::Struct(key)) => {
                        out.push_str(&format!("struct_type = \"{key}\"\n"));
                    }
                    Some(FieldRef::Enum(name)) => {
                        out.push_str(&format!("enum_type = \"{name}\"\n"));
                    }
                    None => {
                        // For scalar fields with array dims, output the element
                        // width (total / product(dims)) so that field_width()
                        // correctly reconstructs the total.
                        let w = if f.array_dims.is_empty() {
                            f.width
                        } else {
                            f.width / total_elements(&f.array_dims)
                        };
                        out.push_str(&format!("width = {w}\n"));
                    }
                }
                emit_dims(&mut out, &f.array_dims);
            }
            out.push('\n');
        }
    }

    // Mappings.
    if !mappings.is_empty() {
        out.push_str(
            "# ── Signal Mappings ───────────────────────────────────────────────────────────\n\n",
        );
        for m in mappings {
            out.push_str("[[mappings]]\n");
            out.push_str(&format!("pattern = \"{}\"\n", m.pattern));
            out.push_str(&format!("struct_type = \"{}\"\n", m.struct_type));
            let total_elems = total_elements(&m.array_dims);
            if let Some(s) = struct_by_key.get(m.struct_type.as_str()) {
                out.push_str(&format!("num_bits = {}\n", s.total_width * total_elems));
            }
            emit_dims(&mut out, &m.array_dims);
            out.push('\n');
        }
    }

    out
}

/// Emit array dimension info to the TOML output.
/// Uses `array_size` for 1D arrays (backward compat) and `array_dims` for 2D+.
fn emit_dims(out: &mut String, dims: &[u32]) {
    match dims.len() {
        0 => {}
        1 => {
            out.push_str(&format!("array_size = {}\n", dims[0]));
        }
        _ => {
            let vals: Vec<String> = dims.iter().map(|d| d.to_string()).collect();
            out.push_str(&format!("array_dims = [{}]\n", vals.join(", ")));
        }
    }
}
